### ISSUE TITLE
Changing color doesnt work

### ISSUE THREAD

**Issue by igmerwina** [willianjusten/will-jekyll-template#6]
Hello :smiley: 
I wanna ask how to change the color from _variables.styl?
Because it wont work when i change the main
And is it possible if we want to put image background in the color layout?
Thanks for your help :smile_cat:

**Comment by willianjusten** [comment]
To change the color, you have to do 2 steps:

1 - Change the color `main` from `_variables.styl`
2 - Run the gulp task to compile the css and move to `_site` folder.

---

To change the background you have to change [this line](https://github.com/willianjusten/will-jekyll-template/blob/gh-pages/src/styl/_header.styl#L7) adding your background image.

**Comment by igmerwina** [comment]
if ound this when run `npm install` , but succesfully installed

```
npm WARN package.json willjekylltemplate@1.0.0 No repository field.
/
```

and i found this **error** when trying to run `gulp` , and the color didnt change
im using windows 7 32-bit

``` gulp
[12:20:35] Using gulpfile ~\Desktop\asdasd\gulpfile.js
[12:20:35] Starting 'js'...
[12:20:35] Starting 'stylus'...
[12:20:35] Finished 'stylus' after 9.45 ms
[12:20:35] Starting 'jekyll-build'...
[12:20:35] Starting 'watch'...
[12:20:35] Finished 'watch' after 139 ms
events.js:85
       throw er; // Unhandled 'error' event
             ^
 Error: spawn jekyll ENOENT
     at exports._errnoException (util.js:746:11)
     at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
     at child_process.js:1144:20
     at process._tickCallback (node.js:355:11)
     at Function.Module.runMain (module.js:503:11)
     at startup (node.js:129:16)
     at node.js:814:3
```

**Comment by willianjusten** [comment]
The first warning is normal, that is happening because the node doesn't find the repository on npm and doesn't have a link to github repo.

About the second error:

The problem is with how Node finds executables on Windows. For more details look at this answer:

http://stackoverflow.com/a/17537559

In short, change `cp.spawn('jekyll', ['build'], {stdio: 'inherit'})` to `cp.spawn('jekyll.bat', ['build'], {stdio: 'inherit'})` in order to get spawn to work at [gulpfile line 23](https://github.com/willianjusten/will-jekyll-template/blob/gh-pages/gulpfile.js#L23).

**Comment by igmerwina** [comment]
yups, i'll try later, thankyou so much
